#!/bin/bash
set -e
PORT=$RANDOM
PORT=$((PORT + 1000))

CFG=$1
K=$2
EF=$3
BS=$4
LR=$5

if [ -z "$BS" ]; then
    BS=8
else
    BS=$BS
fi
if [ -z "$LR" ]; then
    LR=2e-4
else
    LR=$LR
fi

NAME=bs${BS}-lr$LR
SKIP="--skip_connection=True"
SCALING="--post_encoder_scale=True"
if [ -z "$CFG" ]; then
    CROSSING="--cross_layer=12 --coalesce_topk=concat --topk_coalesced=False"
else
    if [ "$CFG" == "none" ]; then
        CROSSING=""
    elif [ "$CFG" == "no-affine" ]; then
        CROSSING="--train_post_encoder=False" SCALING=""
    elif [ "$CFG" == "btopk" ]; then
        CROSSING="--activation=batchtopk"
    elif [ "$CFG" == "btopk-noskip" ]; then
        CROSSING="--activation=batchtopk --train_post_encoder=False" SCALING="" SKIP=""
    elif [ "$CFG" == "btopk-tied" ]; then
        CROSSING="--activation=batchtopk --cross_layer=12 --coalesce_topk=concat --topk_coalesced=False"
    elif [ "$CFG" == "nonskip" ]; then
        CROSSING="" SKIP=""
    elif [ "$CFG" == "nonskip-no-affine" ]; then
        CROSSING="--train_post_encoder=False" SCALING="" SKIP=""
    elif [ "$CFG" == "nonskip-tied" ]; then
        CROSSING="--cross_layer=12 --coalesce_topk=concat --topk_coalesced=False" SKIP=""
    elif [ "$CFG" == "tied" ]; then
        CROSSING="--cross_layer=12 --coalesce_topk=concat --topk_coalesced=False"
    elif [ "$CFG" == "source-tied" ]; then
        CROSSING="--cross_layer=12 --per_source_tied=True --topk_coalesced=False"
    elif [ "$CFG" == "source-tied-no-affine" ]; then
        CROSSING="--cross_layer=12 --per_source_tied=True --topk_coalesced=False --train_post_encoder=False" SCALING="" SKIP=""
    elif [ "$CFG" == "source-tied-no-scale" ]; then
        CROSSING="--cross_layer=12 --per_source_tied=True --topk_coalesced=False" SCALING="" SKIP=""
    elif [ "$CFG" == "source-target-tied" ]; then
        CROSSING="--cross_layer=12 --per_source_tied=True --secondary_target_tied=True --topk_coalesced=False"
    elif [ "$CFG" == "source-tied-no-affine" ]; then
        CROSSING="--cross_layer=12 --per_source_tied=True --topk_coalesced=False --train_post_encoder=False" SCALING=""
    elif [ "$CFG" == "tied-no-affine" ]; then
        CROSSING="--cross_layer=12 --coalesce_topk=concat --topk_coalesced=False --train_post_encoder=False" SCALING=""
    elif [ "$CFG" == "nonskip-tied-no-affine" ]; then
        CROSSING="--cross_layer=12 --coalesce_topk=concat --topk_coalesced=False --train_post_encoder=False" SCALING="" SKIP=""
    elif [ "$CFG" == "cross" ]; then
        # CROSSING="--cross_layer=12 --coalesce_topk=per-layer --topk_coalesced=False"
        # CROSSING="--cross_layer=12 --divide_cross_layer=True --coalesce_topk=per-layer --topk_coalesced=False"
        CROSSING="--cross_layer=12 --divide_cross_layer=True"
        # CROSSING="--cross_layer=12"
    elif [ "$CFG" == "clt-noskip" ]; then
        CROSSING="--cross_layer=12 --divide_cross_layer=True --coalesce_topk=per-layer --topk_coalesced=False --train_post_encoder=False" SCALING="" SKIP=""
    else
        echo "Invalid option: $3"
        exit 1
    fi
    NAME=${NAME}-$CFG
fi
if [ -z "$EF" ]; then
    EF=128
else
    EF=$EF
fi
NAME=${NAME}-ef$EF
if [ -z "$K" ]; then
    K=16
else
    K=$K
fi
NAME=${NAME}-k$K

if [ -z "$OPTIMIZER" ]; then
    OPTIMIZER="adam"
else
    NAME=${NAME}-${OPTIMIZER}
fi

if [ -z "$B1" ]; then
    B1=0.9
else
    NAME=${NAME}-b1$B1
fi

SAVE_ARGS="--save_every 100000000000"
if ! [ -z "$DO_SAVE" ]; then
    if [ "$DO_SAVE" == "1" ]; then
        SAVE_ARGS="--save_every 2000"
    else
        SAVE_ARGS="--save_every $DO_SAVE"
    fi
fi

if ! [ -z "$RESUME" ]; then
    RESUME="--resume"
fi

if ! [ -z "$FINETUNE" ]; then
    FINETUNE="--finetune checkpoints/gpt2-sweep/$NAME$name"
fi

if ! [ -z "$BF16" ]; then
    extra="$extra --dtype bfloat16"
    NAME=$NAME-bf16
fi

N_DEVICE_CHARS=${#CUDA_VISIBLE_DEVICES}
N_DEVICES=$(( ($N_DEVICE_CHARS + 1) / 2 ))
echo "Using $N_DEVICES devices"
DATASET= #"NeelNanda/pile-10k"
# WANDB_ENTITY=eleutherai uv run python -m sparsify \
WANDB_ENTITY=eleutherai uv run torchrun --master_port $PORT --nproc_per_node gpu -m sparsify \
openai-community/gpt2 $DATASET --ctx_len 128 --filter_bos=True --remove_first_token=True \
--transcode=True $SKIP \
--batch_size=$BS --expansion_factor=$EF --k=$K --tp=$N_DEVICES \
--hookpoints h.0.mlp h.1.mlp h.2.mlp h.3.mlp h.4.mlp h.5.mlp h.6.mlp h.7.mlp h.8.mlp h.9.mlp h.10.mlp h.11.mlp \
--run_name gpt2-sweep/$NAME$name \
$CROSSING \
--b1 $B1 \
$SCALING --normalize_io=True \
$SAVE_ARGS --lr $LR \
--optimizer $OPTIMIZER --lr_warmup_steps 50 $extra \
$RESUME $FINETUNE
# --finetune /mnt/ssd-1/nev/e2e/checkpoints/gpt2-sweep/bs8-lr2e-4-none-ef128-k16/

