#!/usr/bin/env bash

set -e

MODEL_NAME=gpt2
NAME=$1
if [[ "$NAME" == /* ]]; then
    CHECKPOINT_PATH=${NAME:1}
else
    CHECKPOINT_PATH=$PWD/checkpoints/gpt2-sweep/$NAME
fi
NAME=${NAME//\//_}


SCAN=$MODEL_NAME-$NAME
set -e
if [ -z "$pn" ]; then
    pn=alice
fi
PROMPT_NAME=$pn-$MODEL_NAME
if [ -z "$pt" ]; then
    # pt="In another moment, down went Alice after it, never once considering how in the world she was to get out again."
    pt="<|endoftext|>The quick brown fox jumps over the lazy"
fi
PROMPT_TEXT=$pt

SAVE_DIR=$PWD/results/gpt2-eval/$NAME/$PROMPT_NAME
mkdir -p $SAVE_DIR

# PROMPT_TEXT="In another moment, down went Alice after it, never once considering how in the world she was to get out again."
cd ../attribution_graph
uv run python -m attribute \
--cache_path=nowhere \
--name $PROMPT_NAME \
--scan "$SCAN" \
"$PROMPT_TEXT" \
--cache_features=False --save_graph=False \
--save_dir=$SAVE_DIR \
--transcoder_path="$CHECKPOINT_PATH" --model_name="$MODEL_NAME" \
${@:2}

