#!/bin/bash
set -e
source_name=$1
target_name=$2
branch=$3
if [ -z "$source_name" ] || [ -z "$target_name" ]; then
    echo "Usage: $0 <source_name> <target_name>"
    exit 1
fi
if [ -z "$branch" ]; then
    branch="main"
fi
repo_id="EleutherAI/$target_name"
huggingface-cli upload $repo_id scripts/null nothing --revision $branch
huggingface-cli upload-large-folder $repo_id checkpoints/$source_name --repo-type model --revision $branch --exclude 'optimizer_*.pt'

